#! /usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

cp ~/dev/pellucidanalytics/bootswatch/pellucid-dark/bootstrap.css ~/dev/pellucidanalytics/store/client/lib/bootswatch/pellucid-dark.css
cp ~/dev/pellucidanalytics/bootswatch/pellucid-dark/bootstrap.min.css ~/dev/pellucidanalytics/store/client/lib/bootswatch/pellucid-dark.min.css
